# tcp:
  # routers:
    # passeverything:
      # rule: HostSNI(`*`)
      # entrypoints: https
      # service: frontend
      # tls:
        # passthrough: true
  # services:
    # frontend:
      # loadBalancer:
        # servers:
          # - address: '172.19.0.1:443'

http:
  ## EXTERNAL ROUTING - use if you want to proxy something manually ##
  routers:
    synology:
      entryPoints:
        - https
      rule: 'Host(`synology.DOMAIN`)'
      service: synology
        
  ## SERVICES ##
  services:
    synology:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: https://172.19.0.1:2053
        passHostHeader: true

  # allow self-signed certificates for proxied web services
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true

  ## MIDDLEWARES ##
  middlewares:
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          defaultDecisionSeconds: 60
          crowdsecMode: live
          crowdsecAppsecEnabled: false # <--- here you can enable appsec waf
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          crowdsecLapiKey: xjRMzALDmBlk4yzkX98jO03dY0GBzWMaiLnLsh2D3H0
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiScheme: http
          crowdsecLapiTLSInsecureVerify: false
          forwardedHeadersTrustedIPs:
            # private class ranges
            - 127.0.0.1/32
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 100.0.0.0/8
          clientTrustedIPs:
            # private class ranges
            - 127.0.0.1/32
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 100.0.0.0/8

# Only use secure ciphers - https://ssl-config.mozilla.org/#server=traefik&version=2.9&config=intermediate&guideline=5.6
tls:
  options:
    default:
      #sniStrict: true # prevents leaking default cert; see https://doc.traefik.io/traefik/v2.2/https/tls/#strict-sni-checking
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
